Fix/navegation
Hortali/Hortali-App pull request #46
Opened 2022-10-27 20:16 UTC by batistagc

### **Certifique-se de que:**

- [x]  Dei um **`update from dev’** antes de criar esse PR;
- [x]  Código esta comentado;
- [x]  Se o PR está indo para a dev;
- [ ]  Inseri as pessoas responsáveis pela tarefa;
- [x]  Não coloquei ninguém em específico para revisar.

### **Qual é o propósito desse Pull Request?**
Inserir gestos nativos de retorno na navegação do App.

### **Comentários adicionais.**
Foi implementada uma NavigationController para acessar os gestos nativos de navegação.

2022-10-28 06:48 UTC, Gui25Reis requested changes
ATENÇÃO:

1.  Veja o template da view controller para lidar com a questão da navigation

2. A tab bar não deve aparecer quando entra nas páginas de informações

3. Eu particularmente não consegui fazer voltar a tela, no fim não resolveu o problema pra mim.
(Não sei porque)

Tenta resolver as questões que precisa e testa de novo!

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/General/Extensions/UINavigationController+GestureRecognizer.swift
> +//
Esse arquivo não deve existir

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/Favorite/FavoriteViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
De acordo com o nosso template em padronizações do Notion existe um método chamado setupNavigation que nele é configurado as configurações.

Esse método é chamado na viewDidLoad

Coloque essa linha nessa função!

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/Favorite/FavoriteViewController.swift
> +        let navigation = UINavigationController(rootViewController: InfoGardenController(with: selectedCell))
Não está usando essa variável, apagar essa linha

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/Favorite/FavoriteViewController.swift
> +        navigation.modalPresentationStyle = .fullScreen
Como não está usando essa variável, também apagar essa linha

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/Food/FoodController.swift
> +        self.navigationController?.isNavigationBarHidden = true
Não está de acordo com o padronização!! Esse problema é o mesmo comentado acima

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/Food/FoodController.swift
> +
Não entendi esse espaçamento a mais que foi adicionado

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/Food/FoodController.swift
> +        let navigation = UINavigationController(rootViewController: InfoFoodController(with: selectedCell))
Não está usando essa variável!

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/Food/FoodController.swift
> +        navigation.modalPresentationStyle = .fullScreen
Apagar essa linha também

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/Main/MainController.swift
> +        nav.navigationBar.prefersLargeTitles = true
Não faz sentido definir que a nav bar vai ter título grande já que nem vai ser usado a nav bar.

Cuidado com código copiado, entenda ele antes de copiar!

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/InfoGarden/InfoGardenController.swift
> +        self.navigationController?.isNavigationBarHidden = true
De acordo com o nosso template em padronizações do Notion existe um método chamado setupNavigation que nele é configurado as configurações.

Esse método é chamado na viewDidLoad

Coloque essa linha nessa função!

2022-10-28 06:48 UTC, Gui25Reis commented on Hortali-App/iOS-App/Screens/InfoFood/InfoFoodController.swift
> +        self.navigationController?.isNavigationBarHidden = true
De acordo com o nosso template em padronizações do Notion existe um método chamado setupNavigation que nele é configurado as configurações.

Esse método é chamado na viewDidLoad

Coloque essa linha nessa função!

2022-10-28 17:25 UTC, thallissousa commented on Hortali-App/iOS-App/Screens/Favorite/FavoriteViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
De acordo

2022-10-28 20:47 UTC, thallissousa commented on Hortali-App/iOS-App/General/Extensions/UINavigationController+GestureRecognizer.swift
> +//  UINavigationController+GestureRecognizer.swift
Mudar o cabeçalho

2022-10-29 02:41 UTC, Gui25Reis approved these changes
Código revisado e concertado!

2022-10-29 02:41 UTC, merged